generate_initial_keywords:
  description: >
    1. Generate an initial list of exactly 10 diverse, short keywords related to {initial_topic}.
    2. Use only your knowledge and creativity. Do not use any external tools or data sources.
    3. Each keyword must be 1-3 words maximum. No long phrases allowed.
    4. Ensure each keyword is relevant to the {initial_topic} niche and has potential for blog content creation.
    5. The 10 keywords should collectively cover a broad domain within the niche, ensuring variety and representation of different subcategories or aspects of the topic.
    6. Make sure the keywords capture a wide range of potential content areas within the {initial_topic} niche.
  expected_output: >
    A numbered list of exactly 10 keywords that cover various aspects of the {initial_topic} niche.
    Format:
    1. [Keyword 1]
    2. [Keyword 2]
    ...
    10. [Keyword 10]
  agent: keyword_research_agent

expand_and_analyze_keywords:
  description: >
    1. Use the KeywordExpansionTool to expand each of the 10 initial keywords individually. Run the tool 10 times, once for each keyword. This is the only allowed use of the KeywordExpansionTool.
    2. Compile all expanded keywords into a single list.
    3. Analyze all expanded keywords based on:
       a. Estimated search volume 
       b. Competition level 
       c. Relevance to the blog's target audience 
    4. From all expanded keywords, identify the top 100 keywords overall based on your analysis.
    5. From these 100, select the top 10 keywords for deeper analysis. Use the GoogleTrendsDataForSEOTool only for this step to compare trending data if CompS scores are close.
    6. Provide clear reasoning for your selection of the top 100 and top 10 keywords.
  expected_output: >
    1. A list of the top 100 keywords with the following format for each:
       [Keyword] - Search Volume:  | Competition:  | Relevance: 
    2. A separate list of the top 10 keywords selected for deeper analysis, including trend data if used.
    3. A brief explanation (2-3 sentences) for why each of the top 10 keywords was selected.
  agent: keyword_research_agent

perform_deep_dive_analysis:
  description: >
    For each of the top 10 keywords:
    1. Use the SerperDevScraper to gather SERP data. Include the top 5 ranking pages for each keyword.
    2. Use the AIWebSearch tool to gather additional insights and context about the keyword and its usage.
    3. Analyze and report on:
       a. Search intent (Informational/Navigational/Transactional/Commercial)
       b. Content gaps in existing top-ranking articles
       c. Potential for long-form blog posts 
       d. Opportunities for a series of related articles (Yes/No, with brief explanation)
    4. Provide a competitor analysis of the top 3 ranking pages for each keyword.
    5. Recommend at least 3 specific content ideas for each keyword.
    Note: Do not use the KeywordExpansionTool or GoogleTrendsDataForSEOTool in this task.
  expected_output: >
    For each of the 10 keywords, provide a structured report containing:
    1. SERP data for top 5 ranking pages
    2. AIWebSearch insights
    3. Analysis of search intent, content gaps, long-form potential, and series opportunities
    4. Competitor analysis of top 3 ranking pages
    5. 3 specific content recommendations
  agent: keyword_research_agent

generate_blog_content_ideas:
  description: >
    1. Review the keyword research results and deep-dive analysis.
    2. Generate exactly 20 unique blog article ideas.
    3. For each idea, provide:
       a. A catchy title (max 10 words)
       b. 2-3 target keywords (chosen from the top 100 list)
       c. Suggested blog post format (e.g., listicle, how-to guide, case study)
       d. A brief 2-3 sentence outline
       e. Estimated search volume potential 
    4. Ensure a mix of different post types (at least 5 different formats).
    5. Cover various aspects related to the main topic, not just the top 10 keywords.
    Note: Do not use the KeywordExpansionTool or GoogleTrendsDataForSEOTool in this task.
  expected_output: >
    A numbered list of 20 blog content ideas, each containing all required elements (a-e) as specified above.
  agent: content_ideation_agent

identify_blog_content_trends:
  description: >
    1. Use the AIWebSearch tool to gather current trend data related to the {initial_topic} niche.
    2. Analyze and report on:
       a. Top 5 popular blog post formats in the niche
       b. Top 5 emerging subtopics within the niche
       c. Top 5 audience preferences and pain points
       d. Top 5 successful content strategies used by top bloggers in the niche
       e. Top 5 social media trends related to the topic
    3. For each category (a-e), provide:
       - A brief description of the trend
       - An example of its successful implementation
       - A suggestion for how to incorporate it into our blog content strategy
    Note: Do not use the KeywordExpansionTool or GoogleTrendsDataForSEOTool in this task.
  expected_output: >
    A structured report covering all 5 categories (a-e) as specified, with clear headings and subheadings.
    Include a summary section with the top 3 overall trends to focus on, based on your analysis.
  agent: trend_analysis_agent

compile_comprehensive_blog_strategy_report:
  description: >
    Compile all findings into a detailed report, including:
    1. Executive Summary (max 500 words)
    2. Initial 10 keywords and their relevance
    3. Top 100 expanded keywords with metrics
    4. In-depth analysis of the top 10 keywords
    5. 20 blog content ideas
    6. Trend analysis and its implications
    7. Actionable recommendations for blog content creation, including:
       a. Content calendar for the next 3 months (12 post ideas with proposed publication dates)
       b. SEO strategy for implementing the identified keywords
       c. Social media strategy to promote the content
    8. Conclusion with a prioritized list of 5 next steps for implementing the blog strategy
    Note: This task does not require the use of any external tools. Use only the information gathered in previous tasks.
  expected_output: >
    A comprehensive, well-structured report containing all elements specified above, 
    with clear headings, subheadings, and a table of contents. The report should be 
    in Markdown format for easy conversion to other document types.
  agent: report_generation_agent
  output_file: blog_strategy_report.md
